services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/libris_db
      - SPRING_DATASOURCE_USERNAME=libris_dev
      - SPRING_DATASOURCE_PASSWORD=shhhh
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - libris-network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=libris_db
      - POSTGRES_USER=libris_dev
      - POSTGRES_PASSWORD=shhhh
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - libris-network

volumes:
  postgres_data:

networks:
  libris-network:
